import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
import HeaderMenu from "@/components/header-menu/HeaderMenu";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
        <body>
          <header>
            <HeaderMenu />
          </header>{children}
        </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
      
    </html>
  );
}
